### ISSUE TITLE
Issues encountered during formal training after pre-training the weight files.

### ISSUE THREAD

**Issue by SASasfc** [LS4GAN/uvcgan2#26]
Hello！
![1712554374389](https://github.com/LS4GAN/uvcgan2/assets/166362110/59ecbd9d-550a-477b-8609-ba426c8b3313)
After obtaining the pre-trained weight file in the picture, when I try to train the train_cat2dog_translation.py formally, I always encounter this OSError: Failed to find fully trained model in 'outdir/afhq_resized_lanczos/model_m(simple-autoencoder)_d(None)_g(vit-modnet)_pretrain-uvcgan2' for transfer: [Errno 2] No such file or directory: 'outdir/afhq_resized_lanczos/model_m(simple-autoencoder)_d(None)_g(vit-modnet)_pretrain-uvcgan2/net_gen_ab.pth' error. But the pre-trained weight file I got doesn't have one called net_gen_ab.pth, should I rename net_encoder.pth to net_gen_ab.pth?
![1712554392313](https://github.com/LS4GAN/uvcgan2/assets/166362110/5272d997-e8d7-4c01-b249-8b3705b85f1f)

**Comment by usert5432** [comment]
Hi @SASasfc,

This is very strange behavior indeed. I do not think a simple renaming will work -- it looks like the model's configuration file got corrupted. The solution to this problem will depend on your usecase.

If you simply want to use a pre-trained model that we provide, then you could try to do the following;
1. Move the existing pre-trained model to a safe location.
2. Download our weights with `scripts/download_model.sh afhq_pretrain --full`
3. Try cat2dog training again.

If would like to run the pre-training yourself -- then you could try doing the following:
1. Save a copy of your pre-trained model just in case something goes wrong.
2. Remove `config.json` file from your pre-trained model.
3. Run the pre-training script again. The pre-training script should regenerate the correct config, and you will be able to use this model in the subsequent cat2dog training.

Please let me know if the above does not work, if you would like me to elaborate on any of the steps.

**Comment by SASasfc** [comment]
Thank you very much for your answer! ！I am very happy. Maybe what I said before was not clear. First, I trained my own data set, but using the cat2dog code, I first ran pretrain_afhq.py. After completing the 500epoch training, the weight files in the picture above were generated and I saw The content of these weight files is similar to the afhq_pretrain --full weight file you officially provided about cat2dog. It seems that there are no weight files missing after pre-training. There are also files such as net_encoder.pth and opt_enconder.pth, so I will continue to run After adding train_cat2dog_translation.py, the above-mentioned error about the missing file net_gen_ab.pth appeared, so I had questions.
1. After completing the pre-training, will the net_gen_ab.pth file be needed to run the formal training code? Because I saw that the afhq_pretrain --full weight file you provided did not generate a weight file with this name. Then I found the net_gen_ab.pth file in afhq_cat2dog_full.zip. I was very surprised that this folder should not be created after the formal training is completed. Do you have a weight file? But I am just about to start formal training now. Now when I run it, it says that I don’t have net_gen_ab.pth, net_gen_ba.pth, net_disc_a.pth, etc. I am confused.
![90de1f280df392617cdb3dc20f66d6c](https://github.com/LS4GAN/uvcgan2/assets/166362110/e4aeeab7-6eee-40a2-9ad7-59b7c5c692d8)
Maybe I don't fully understand the code of train_cat2dog_translation.py. I hope you can help me solve this problem.thank you

**Comment by usert5432** [comment]
Thank you for the elaboration @SASasfc!

> After completing the pre-training, will the net_gen_ab.pth file be needed to run the formal training code?

I don't think the pre-training script is supposed to generate this file. Likewise, this file is not needed to run the formal training code.

I think, we were not clear about our terminology, and I apologize for that. Specifically,  we used the term "pre-training" very loosely to mean two separate things:
1. Sometimes, when we say "pre-training", we refer to the first stage of the UVCGANv2 training procedure. That is, pre-training the translation generators on the task of masked image inpainting. Let me refer to this kind of **"pre-training"** as the **"pretext"** to avoid confusion.
2. Other times, when we say "pre-trained" models, we simply mean reference style transfer models, trained by us.
3. Yet other times, we can say "pre-trained" model and refer to the "pretext" models trained by us.

With this in mind, let me try to touch on your question
>  I first ran pretrain_afhq.py. ...The content of these weight files is similar to the afhq_pretrain --full weight pretrain_afhq.py

Yes, this is the expected behavior. The "pretrain_afhq" scripts runs the "pretext" training, so it only produces "encoder" models, but does not produce "gen_ab" nor "gen_ba" ("translation") models.

> Because I saw that the afhq_pretrain --full weight file you provided did not generate a weight file with this name. Then I found the net_gen_ab.pth file in afhq_cat2dog_full.zip.

Yep, this is also expected. "afhq_pretrain --full" downloads "pretext" model. But "afhq_cat2dog_full" is a "translation" model, so it has "gen_ab" and "gen_ba".

> Now when I run it, it says that I don’t have net_gen_ab.pth, net_gen_ba.pth, net_disc_a.pth, etc. I am confused.

This is likely because "encoder" files do not have a correct configuration file (`config.json`). Sometimes this may happen if one moves `*.pth` files around without copying their `config.json`. It is also possible that the training scripts were misconfigured. if you could share your "pretext" script (pretrain_afhq.py) and "translation" script (train_cat2dog_translation) -- I can point to the areas that need to be changed to fix this. If you do not wish to share the full scripts -- you could provide only parts that describe the following parameters:
```
'label'
'outdir'
'transfer' # And the path to the transfer model.
```

Sorry if I am not answering your question, or if this is still unclear. Please feel free to ask follow up questions if you need me to elaborate on anything.

**Comment by SASasfc** [comment]
[train_cat2dog_translation.zip](https://github.com/LS4GAN/uvcgan2/files/14927505/train_cat2dog_translation.zip)

Of course, I'd be happy to give you my part of the code, and I hope you can help me see what caused the problem. 
First of all, let me explain the files in the archive separately:

1. config file: Among them, the config file in the compressed package is automatically generated after pretext, and every time I run pretext, I delete the previous config file to prevent the configuration address from being incorrect

2. 2. Picture: The picture points out my corresponding address, that is, the weight parameter .pth generated after pretext, and the checkpoints folder is the picture I sent to you for the first time with 500epoch.pth and 400epoch.pth. Also, at first I didn't have model_m (simple-autoencoder), _d (None), _g (vit-modnet), _pretrain-uvcgan2 folders in my afhq_resized_lanczos folder, because I ran the pretext file and then ran the train_cat2dog_translation.py file with an error saying I don't have this folder So I created my own train_cat2dog_translation.py code and then continued running. I don't know if it's caused by this problem.

I probably don't fully understand the phrase "This is likely because "encoder" files do not have a correct configuration file (config.json). Sometimes this may happen if one moves *.pth files around without copying their config.json. It is also possible that the training scripts were misconfigured." so I need to rewrite the code once pretrain_afhq.py and then regenerate the new config.json？
thank you！！

**Comment by usert5432** [comment]
Hi @SASasfc,

Thank you for sharing your scripts. I have just looked over them and tried running the "pretext" and "translation" scripts. They look ok to me. The "translation" script fails with the message:
```
OSError: Failed to find fully trained model in 'outdir/afhq_resized_lanczos/model_m(simple-autoencoder)_d(None)_g(vit-modnet)_pretrain-uvcgan2' for transfer: [Errno 2] No such file or directory: 'outdir/afhq_resized_lanczos/model_m(simple-autoencoder)_d(None)_g(vit-modnet)_pretrain-uvcgan2/net_encoder.pth'
```
This error is an expected behavior, since I do not have a trained "pretext" model (the one that creates "net_encoder.pth"). However, I do not get an error similar to yours.

The `config.json` file that you have shared with me also looks good.

To further investigate this issue, may I ask you please to do the following:
1. run your "pretext" script and copy here any errors that it reports.
2. run your "translation" script and copy here any errors that it reports. Please make sure that you are running this script from the same directory as the "pretext" script.

> I probably don't fully understand the phrase "This is likely because "encoder" files do not have a correct configuration file (config.json). Sometimes this may happen if one moves *.pth files around without copying their config.json. It is also possible that the training scripts were misconfigured." so I need to rewrite the code once pretrain_afhq.py and then regenerate the new config.json？

I think the error that you observe may happen if one does the following:
1. Trains a "pretext" model with "pretrain_afhq"
2. Replaces `config.json` file of a "pretext" model by a `config.json` file of a "translation" model.

If this is what happened, then the simplest solution would be to simply remove `config.json` of the "pretext" model and run "pretrain_afhq" again. The "pretrain_afhq" will regenerate the correct `config.json` and everything should work fine.

Please feel free to reach out if you need more information.

**Comment by SASasfc** [comment]
thank you  i will try again！！
